apiVersion: v1
kind: Namespace
metadata:
  name: push-fight
  labels:
    istio-injection: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: push-fight-app
  namespace: push-fight
  labels:
    app: push-fight-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: push-fight-app
  template:
    metadata:
      labels:
        app: push-fight-app
    spec:
      containers:
      - name: app
        image: push-fight-app:latest
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "2"
            memory: "2Gi"
